version: "3.0"
services:
  wordpress:
    image: wordpress:latest
    environment:
      - WORDPRESS_DB_USER=wp_user
      - WORDPRESS_DB_PASSWORD=wp_password
    ports:
      - 8080:80
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=db_password
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=wp_password
      - MYSQL_DATABASE=wordpress
